- build: 3.4.8/centos/7
  image:
    - mesoscloud/zookeeper:3.4.8-centos-7
    - mesoscloud/zookeeper:3.4.8-centos
    - mesoscloud/zookeeper:3.4.8
    - mesoscloud/zookeeper:latest

- build: 3.4.8/ubuntu/14.04
  image:
    - mesoscloud/zookeeper:3.4.8-ubuntu-14.04
    - mesoscloud/zookeeper:3.4.8-ubuntu

- build: 3.4.7/centos/7
  image:
    - mesoscloud/zookeeper:3.4.7-centos-7
    - mesoscloud/zookeeper:3.4.7-centos
    - mesoscloud/zookeeper:3.4.7

- build: 3.4.7/ubuntu/14.04
  image:
    - mesoscloud/zookeeper:3.4.7-ubuntu-14.04
    - mesoscloud/zookeeper:3.4.7-ubuntu


- tests:
    - cmd: zkServer.sh print-cmd

    - cmd: test "`tail -n1 /opt/zookeeper/conf/zoo.cfg`" = 'server.1=127.0.0.1:2888:3888'
      env:
        - SERVERS=127.0.0.1

    - cmd: test "`tail -n1 /opt/zookeeper/conf/zoo.cfg`" = 'server.3=192.168.33.3:2888:3888'
      env:
        - SERVERS=192.168.33.1,192.168.33.2,192.168.33.3
